export const ACTUALIZAR_TOTAL = 'ACTUALIZAR_TOTAL';
export const CANTIDAD_PRODUCTO = 'CANTIDAD_PRODUCTO';
export const SELECCIONAR_CLIENTE = 'SELECCIONAR_CLIENTE';
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO';